[workspace]
members = ["ewe", "ewe-build", "commons"]

[workspace.dependencies]
anyhow = "1.0.68"
clap = { version = "4.0.32", features = ["derive"] }
ewe-commons = { path = "commons" }
mlua = { version = "0.8.6", features = ["lua54", "serialize"] }
once_cell = "1.17.0"
reqwest = "0.11.13"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
tempfile = "3.3.0"

[profile.release]
strip = true
opt-level = "z"
codegen-units = 1
panic = "abort"
lto = true
