[package]
name = "ewe-commons"
version = "0.1.0"
edition = "2021"

[lib]
path = "lib.rs"

[dependencies]
serde = { version = "1.0.152", features = ["derive"] }
thiserror = "1.0.38"
url = { version = "2.3.1", features = ["serde"] }
mlua = { workspace = true, optional = true }
